runtime: python310

instance_class: F4

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PYTHONUNBUFFERED: "True"

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50
  
# Add build step to install packages from the cloud-compatible requirements file
build_env_variables:
  GOOGLE_ENTRYPOINT: "pip install -r requirements.txt && gunicorn -b :$PORT app:app"