steps:
# Install dependencies using the cloud-compatible requirements file
- name: 'python:3.10'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '--user']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA', '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'exercisedeploy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--min-instances'
  - '1'
  - '--memory'
  - '2Gi'
  - '--cpu'
  - '2'
  - '--set-env-vars'
  - 'PYTHONUNBUFFERED=1,EVENTLET_NO_GREENDNS=yes'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '300s'


options:
  logging: CLOUD_LOGGING_ONLY

# Store images
images:
- 'gcr.io/$PROJECT_ID/ai-fitness-trainer:$COMMIT_SHA'

timeout: '1600s'